version: "3"

networks:
    backend:
        driver: bridge

services:
    # Web server
    www_mjtsc:
        build:
            context: .
        volumes:
            # excluded from sync
            #- '/var/www/src/storage/logs'
            - '/var/www/src/storage/framework'
            # sync
            - ../src:/var/www/src:cached
        networks:
            - backend